### ISSUE TITLE
ImportError: cannot import name SpooledTemporaryFile

### ISSUE THREAD

**Issue by jfinnson** [emlynoregan/appenginetaskutils#3]
Hi, the taskutils library has been working great for us. However, recently all of our developers are suddenly getting this error when we run dev_appserver:

(Partial trace, version 0.1.7 and 0.4.1)

import taskutils
        |   File "/app/libs/taskutils/__init__.py", line 3, in <module>
        |     import taskutils.task as taskpy
        |   File "/app/libs/taskutils/task.py", line 7, in <module>
        |     import flask
        |   File "/app/libs/flask/__init__.py", line 17, in <module>
        |     from werkzeug.exceptions import abort
        |   File "/app/libs/werkzeug/__init__.py", line 151, in <module>
        |     __import__('werkzeug.exceptions')
        |   File "/app/libs/werkzeug/exceptions.py", line 71, in <module>
        |     from werkzeug.wrappers import Response
        |   File "/app/libs/werkzeug/wrappers.py", line 37, in <module>
        |     from werkzeug.formparser import FormDataParser, default_stream_factory
        |   File "/app/libs/werkzeug/formparser.py", line 14, in <module>
        |     from tempfile import SpooledTemporaryFile
        | ImportError: cannot import name SpooledTemporaryFile

We are getting this error on all branches (old and new). With old and new versions of gcloud.
Google's official response is: "tempfiles are one of the features that AppEngine Standard does not support".

We are very confused how this issue could suddenly start appearing.

We solved this temporarily by adding the following code to appengine_config.py, but we would like to know more about this issue:
`import tempfile
tempfile.SpooledTemporaryFile = tempfile.TemporaryFile`

**Comment by emlynoregan** [comment]
I'll have a look. Could it be a new version of werkzeug or flask causing an issue, or some dependency of those libraries? You might be able to work around this by locking down the versions of dependencies in your requirements.txt

**Comment by emlynoregan** [comment]
This is happening to everyone using Flask, it turns out. The problem does seem to be werkzeug, new version 0.13. The best fix is to downgrade to 0.12.12, ie: add this to your requirements.txt:

werkzeug==0.12.2

More info at stackoverflow:
https://stackoverflow.com/questions/47716196/gae-standard-flask-tutorial-importerror-cannot-import-name-spooledtemporaryfil

But I'll also roll out a new version of appenginetaskutils with this downgrade specified.

**Comment by jfinnson** [comment]
Adding werkzeug == 0.12.2 to requirements.txt solved the problem. Thanks for looking into this quickly.

**Comment by emlynoregan** [comment]
There's a new version, which has this coded into the requirements of the package.
